//
//  DetailViewController.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/25/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import UIKit

class DetailViewController: UIViewController, DetailView {

	var presenter: DetailPresenter?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
