//
//  DetailInteractor.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/25/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import Foundation

protocol DetailUseCase {
    
}

class DetailInteractor: DetailUseCase {
    
    
    init() {
    }
    
    
}
