//
//  HomeRouter.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/24/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//


import Foundation
import UIKit

class HomeRouter {
   enum Destination {
    case Details(movie:Movie),None
    }
    
    var navigationController: UINavigationController?
    // MARK: - Initializer
    
    init() {
        
    }
   
    init(navigationController: UINavigationController) {
        self.navigationController = navigationController
    }
    
    func navigate(to destination: HomeRouter.Destination) {
        let viewController = makeViewController(for: destination)
        navigationController?.pushViewController(viewController, animated: true)
    }
    
     func root(to destination: HomeRouter.Destination) {
         let viewController = makeViewController(for: destination)
         navigationController?.viewControllers = [viewController]
     
         UIApplication.shared.keyWindow?.rootViewController = navigationController
     }
    
    func present(to destination: HomeRouter.Destination) {
        let viewController = makeViewController(for: destination)
        navigationController?.present(viewController, animated: true) {}
    }
    
    func detailViewController(movie:Movie) -> DetailViewController {
        let vc:DetailViewController = UIViewController.instanceXib()
        DetailBuilder().build(vc: vc, navigator: self.navigationController!, movie: movie)
        return vc
    }

    func makeViewController(for destination: Destination) -> UIViewController {
        switch destination {
        case .Details(let movie):
            return detailViewController(movie: movie)
        case .None:
            return UIViewController()
        }
    }
}

