//
//  DetailInteractor.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/25/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import Foundation

protocol DetailUseCase {
    func loadMovie()
    func loadMoviePhotos()
    func photoUrlBuilder( photo: Photo) -> String
}

class DetailInteractor: DetailUseCase {
    
    
    private var movie:Movie?
    var presenter:DetailPresenterDelegate?
    
    
    init(movie:Movie) {
        self.movie = movie
        
    }
    func loadMovie()  {
        // If there is any logic done on the object before passing it to the presenter
        presenter?.presentMovie(with: movie ?? Movie())
    }
    
    func loadMoviePhotos() {
        
    }
    func photoUrlBuilder(photo: Photo) -> String {
        return "http://farm​\(photo.farm!)​.static.flickr.com/\(photo.server!)​/\(photo.id!)​_​\(photo.secret!)​.jpg"
    }
    
}
