//
//  HomeViewController.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/24/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import UIKit

class HomeViewController: UIViewController, HomeView {
    
    var presenter: HomePresenter?
    
    @IBOutlet weak var moviesTableView: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        HomeBuilder().build(vc: self, navigator: self.navigationController!)
        self.presenter?.fetchMovies()
    }
    
    func showError(message: String) {
        
    }
    
}
