//
//  HomeInteractor.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/24/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import Foundation



protocol HomeUseCase {
    func parseMoviesFromLocalFile()
}

class HomeInteractor: HomeUseCase {
    
    var presenter:HomePresenterDelegate?
    
    init() {
    
    }
    
    func parseMoviesFromLocalFile() {
        
        let bundle = Bundle(for: type(of: self))
        guard let url = bundle.url(forResource: "movies", withExtension: "json") else {
            presenter?.errorFetchingMovies(error: .NoJsonFile)
            return
        }
        do {
            let json = try Data(contentsOf: url)
            do {
                let responseModel: MoviesResponse = try JSONDecoder().decode(MoviesResponse.self, from: json)
                
               
                presenter?.didFetchMovies(movies: responseModel.movies!)
            } catch {
                presenter?.errorFetchingMovies(error: .ParsingError)
            }
        } catch {
            presenter?.errorFetchingMovies(error: .ParsingError)
        }
        
    }
    
    
}

