//
//  HomeBuilder.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/24/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import Foundation
import UIKit

class HomeBuilder {
    func build(vc: HomeViewController,navigator:UINavigationController) {
        
        let interactor = HomeInteractor()
        let router = HomeRouter(navigationController: navigator)
        vc.presenter = HomePresenter(interactor: interactor, router: router, view: vc)
        
    }
}

