//
//  HomeInteractor.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/24/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import Foundation


typealias ServicesResponse = (Error?,[Movie])

protocol HomeUseCase {
    func parseMoviesFromLocalFile(completation:@escaping( (ServicesResponse)-> Void))
}

class HomeInteractor: HomeUseCase {
    
    init() {
    }
    func parseMoviesFromLocalFile(completation:@escaping( (ServicesResponse)-> Void)) {
        
    }
    
    
}

