//
//  HomeViewController.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/24/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import UIKit

class HomeViewController: UIViewController, HomeView {
    
    var presenter: HomePresenter?
    
    @IBOutlet weak var moviesTableView: UITableView!
    @IBOutlet weak var searchBar: UISearchBar!
    var yearButton: UIBarButtonItem?
    override func viewDidLoad() {
        super.viewDidLoad()
        HomeBuilder().build(vc: self, navigator: self.navigationController!)
        self.presenter?.fetchMovies()
        setUpSearchBar()
        yearButton = UIBarButtonItem(title: "Search By Year", style: .plain, target: self, action: #selector(openYearDialog))
        yearButton?.tintColor = UIColor(hexString: "#FF0E5E")
        navigationItem.rightBarButtonItems = [yearButton!]
        
    }
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        CacheHandler.shared.SaveData(moviesObject: Constant.movieResponse)
        
        
    }
    @objc func openYearDialog() {
        self.presenter?.openYearsPicker()
    }
    
    func setUpSearchBar() {
        searchBar.searchTextField.textColor = .white
        searchBar.delegate = self
        
        if let textFieldInsideSearchBar = self.searchBar.value(forKey: "searchField") as? UITextField,
            let glassIconView = textFieldInsideSearchBar.leftView as? UIImageView {
            
            //Magnifying glass
            glassIconView.image = glassIconView.image?.withRenderingMode(.alwaysTemplate)
            glassIconView.tintColor = .white
        }
    }
    
    func showError(message: String) {
        Toast.showAlert(viewController: self, text: message)
    }
    
}

extension HomeViewController:UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        self.presenter?.search(str:searchText)
        
    }
}
