//
//  DetailView.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/25/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import Foundation
import UIKit
import Cosmos
//MARK: View -
protocol DetailView: class {
    var photosCollection: UICollectionView! { get set }
    var mainImageView: UIImageView! { get set }
    var labelTitle: UILabel! { get set }
    var labelYear: UILabel! { get set }
    var labelGeners: UILabel! { get set }
    var labelCast: UILabel! { get set }
    var ratingView: CosmosView! {get set}
    
    func showError(message:String)
}
