//
//  DetailPresenter.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/25/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import UIKit
import Cosmos
class DetailPresenter: DetailPresenterUseCases {
    
    private var interactor:DetailInteractor?
    private var router:DetailRouter?
    
    //MARK: TO AVOID RETAIN CYCLE
    private weak var view:DetailView?
    
    
    //MARK: Attributes
    private var dataSource:PhotoCollectionViewCellDataSource?
    
    
    init(interactor:DetailInteractor,router:DetailRouter,view:DetailView) {
        self.interactor = interactor
        self.router = router
        self.view = view
    }
    
    
    func loadDetails() {
        interactor?.loadMovie()
    }
    func loadPhotos()  {
        interactor?.loadMoviePhotos()
    }
    
}

extension DetailPresenter :DetailPresenterDelegate{
    func moviesImages(with photos:[Photo]){
        var photos = photos
        if !photos.isEmpty {
            if let base64 = photos.first?.base64 ,!base64.isEmpty {
                let dataDecoded : Data = Data(base64Encoded: base64, options: .ignoreUnknownCharacters)!
                       let decodedimage:UIImage = UIImage(data: dataDecoded)!
                       self.view?.mainImageView!.image = decodedimage
            } else {
                let first = photos.first!.url!
                self.view?.mainImageView!.sd_setImage(with: first as URL?, completed: { (img, e, s, u) in
                    
                })
            }
            
            photos.removeFirst()
            dataSource = PhotoCollectionViewCellDataSource(collection: self.view!.photosCollection, photos: photos,delegate: self)
        }
    }
    
    func failedToLoad(message: String) {
        self.view?.showError(message: message)
    }
    func presentMovie(with movie: Movie) {
        self.view?.labelTitle.text = movie.title!
        var cast = ""
        var geners = ""
        for item in movie.cast! {
            cast = cast + " \(item)"
        }
        for item in movie.genres! {
            geners = geners + " \(item)"
        }
        self.view?.labelCast.text = cast
        self.view?.labelYear.text = "\(movie.year!)"
        self.view?.labelGeners.text = geners
        self.view?.ratingView.rating = Double(movie.rating!)
    }
}

extension DetailPresenter:PhotoCellDelegate {
    func cacheImage(index:Int,base64: String) {
        interactor?.cacheImage(index: index, base64: base64)
    }
    
}


protocol DetailPresenterDelegate {
    func presentMovie(with movie:Movie)
    func moviesImages(with photos:[Photo])
    func failedToLoad(message:String)
}

protocol DetailPresenterUseCases {
    func loadDetails()
}
