//
//  DetailPresenter.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/25/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import UIKit

class DetailPresenter: DetailPresenterUseCases ,DetailPresenterDelegate{
    
    
    private var interactor:DetailInteractor?
    private var router:DetailRouter?
    
    //MARK: TO AVOID RETAIN CYCLE
    private weak var view:DetailView?
    
    
    //MARK: Attributes
    private var dataSource:PhotoCollectionViewCellDataSource?
    
    
    init(interactor:DetailInteractor,router:DetailRouter,view:DetailView) {
        self.interactor = interactor
        self.router = router
        self.view = view
    }
    
    func presentMovie(with movie: Movie) {
        dataSource = PhotoCollectionViewCellDataSource(collection: self.view!.photosCollection, urls: [String]())
    }
    func loadDetails() {
        interactor?.loadMovie()
    }
    
    
    
    
}
protocol DetailPresenterDelegate {
    func presentMovie(with movie:Movie)  
}

protocol DetailPresenterUseCases {
    func loadDetails()
}
