//
//  DetailInteractor.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/25/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import Foundation

protocol DetailUseCase {
    func loadMovie()
}

class DetailInteractor: DetailUseCase {
    
    private var movie:Movie?
    var presenter:DetailPresenterDelegate?
    
    
    init(movie:Movie) {
        self.movie = movie
        
    }
    func loadMovie()  {
        // If there is any logic done on the object before passing it to the presenter
        presenter?.presentMovie(with: movie ?? Movie())
    }
    
    
}
