//
//  DetailBuilder.swift
//  MovieMasterDetail
//
//  Created Mena Gamal on 6/25/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Mena Gamal
//

import Foundation
import UIKit

class DetailBuilder {
    func build(vc: DetailViewController,navigator:UINavigationController,movie:Movie) {
        
        let interactor = DetailInteractor(movie: movie)
        let router = DetailRouter(navigationController: navigator)
        vc.presenter = DetailPresenter(interactor: interactor, router: router, view: vc)
        interactor.presenter = vc.presenter
    }
}

